### ISSUE TITLE
Automatically invite "room monitor" users to the correct Matrix rooms at the correct time

### ISSUE THREAD

**Issue by strugee** [SeaGL/patch#60]
The list of room monitor users would be specified by config, mapping a track to a Matrix ID.

Possibly also consider _kicking_ the room monitor user for the _second_ previous talk, in order to declutter the Element UI and make it easier to find the talk room.

**Comment by AndrewKvalheim** [comment]
Related: 7f495fc2a4449d418b647936948798b1e0241568, f6184cdecbadbf45c25f3de00c3064932e2e3b88
